services:
  backend:
    image: freeapi-server
    build: .
    ports:
      - 8085:8080
    volumes:
      - ./:/usr/src/freeapi
      - /usr/src/freeapi/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo_one_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
    depends_on:
      - mongodb

volumes:
  mongo_one_data: